version: "3.5"

services:
  # Go 应用
  ginblog:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ginblog
    ports:
      - "8000:8000" # Go 应用映射到主机的 8000 端口
    volumes:
      - .:/go/src/ginblog
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/blog
      - REDIS_URL=redis://redis:6379
    networks:
      - gin-blog

  # MySQL 服务
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - "33069:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - gin-blog

  #redis容器 - Redis container
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 36379:6379
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      # 数据文件 - data files
      - ./data/redis/data:/data:rw
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - gin-blog

  #前端网关nginx-gateay
  nginx-gateway:
    image: nginx:latest
    container_name: nginx-gateway
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 8888:8000
    volumes:
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./deploy/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/log:/var/log/nginx
    depends_on:
      - ginblog
    networks:
      - gin-blog

networks:
  gin-blog:
    driver: bridge

volumes:
  mysql_data:
